using System.Reflection;
using System.Runtime.InteropServices;

// In SDK-style projects such as this one, several assembly attributes that were historically
// defined in this file are now automatically added during build and populated with
// values defined in project properties. For details of which attributes are included
// and how to customise this process see: https://aka.ms/assembly-info-properties


// Setting ComVisible to false makes the types in this assembly not visible to COM
// components.  If you need to access a type in this assembly from COM, set the ComVisible
// attribute to true on that type.

[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM.

[assembly: Guid("1ed9e6d2-cc20-4cd1-a285-13eb41161dce")]


// Autogenerated in TourneyPal.Assemblyinfo.cs
[assembly: AssemblyCompany("Christina Trialoni")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyProduct("TourneyPal")]
[assembly: AssemblyTitle("TourneyPal")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]



[assembly: AssemblyVersion("0.0.0.14")]
[assembly: AssemblyFileVersion("0.0.0.14")]
[assembly: AssemblyInformationalVersion("0.0.0.14")]
